### ISSUE TITLE
website kerneltest: Home does not show the 5.16 kernels currently being test

### ISSUE THREAD

**Issue by heis2201** [jmflinuxtx/kerneltest-harness#33]
https://apps.fedoraproject.org/kerneltest/ does not show the 5.16 series that is currently being tested...

The site exists: https://apps.fedoraproject.org/kerneltest/kernel/5.16.2-200.fc35.x86_64, it's just not populated on Home

**Comment by jmflinuxtx** [comment]
This is by design, The front page is meant to show official kernels, and to keep it from being abused, it only updates when a kernel is tested by the official infrastructure. As test week kernels are actually built as official updates, I actually have to go out of my way a bit to keep the results off of that page.
